begin;

-- v0.4 adds a venture layer between tenant organizations and operational
-- workspaces. It is additive so active v0.3 agents and work leases continue to
-- use their existing immutable workspace identities.

create table public.ventures (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null
    references public.organizations(id) on delete cascade,
  slug text not null
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(trim(name)) between 1 and 160),
  venture_type text not null default 'operating'
    check (venture_type in ('operating', 'client', 'proof_of_concept', 'sandbox')),
  stage text not null default 'validation'
    check (stage in ('idea', 'validation', 'launch', 'operating', 'scaling', 'paused', 'archived')),
  thesis text,
  business_model text,
  status text not null default 'active'
    check (status in ('active', 'paused', 'archived')),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug),
  unique (organization_id, id)
);

alter table public.workspaces
  add column venture_id uuid references public.ventures(id) on delete restrict;

alter table public.workspaces drop constraint if exists workspaces_kind_check;
alter table public.workspaces
  add constraint workspaces_kind_check check (
    kind in ('business', 'department', 'client', 'internal')
  );

create or replace function control_plane_private.validate_workspace_venture()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.venture_id is not null and not exists (
    select 1 from public.ventures v
    where v.id = new.venture_id
      and v.organization_id = new.organization_id
      and v.status <> 'archived'
  ) then
    raise exception 'workspace venture must belong to the same active tenant';
  end if;
  return new;
end;
$$;

create trigger workspaces_validate_venture
before insert or update of venture_id, organization_id on public.workspaces
for each row execute function control_plane_private.validate_workspace_venture();

-- Existing business workspaces become root workspaces for derived ventures.
-- IDs are generated by Postgres and resolved by tenant/slug, never hard-coded.
insert into public.ventures (
  organization_id, slug, name, venture_type, stage, thesis, metadata
)
select
  w.organization_id,
  w.slug,
  w.name,
  'operating',
  'validation',
  w.purpose,
  jsonb_build_object(
    'migrated_from_workspace_id', w.id,
    'migration', 'v0.4'
  )
from public.workspaces w
where w.kind = 'business'
on conflict (organization_id, slug) do nothing;

update public.workspaces w
set venture_id = v.id
from public.ventures v
where w.kind = 'business'
  and v.organization_id = w.organization_id
  and v.slug = w.slug
  and w.venture_id is null;

create or replace function control_plane_private.prevent_venture_reassignment()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.venture_id is distinct from old.venture_id then
    raise exception 'venture assignment is immutable';
  end if;
  return new;
end;
$$;

create trigger workspaces_prevent_venture_reassignment
before update of venture_id on public.workspaces
for each row execute function control_plane_private.prevent_venture_reassignment();

create table public.agent_workspace_memberships (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  membership_role text not null default 'worker'
    check (membership_role in ('owner', 'executive', 'manager', 'worker', 'reviewer', 'observer')),
  can_claim_work boolean not null default true,
  can_delegate_work boolean not null default false,
  status text not null default 'active'
    check (status in ('active', 'suspended', 'revoked')),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (agent_id, workspace_id)
);

create or replace function control_plane_private.validate_agent_membership()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  home_organization_id uuid;
  target_organization_id uuid;
begin
  select w.organization_id into home_organization_id
  from public.agents a
  join public.workspaces w on w.id = a.workspace_id
  where a.id = new.agent_id;

  select w.organization_id into target_organization_id
  from public.workspaces w
  where w.id = new.workspace_id;

  if home_organization_id is null
     or target_organization_id is null
     or home_organization_id <> target_organization_id then
    raise exception 'agent memberships cannot cross tenant organizations';
  end if;
  return new;
end;
$$;

create trigger agent_workspace_memberships_validate_tenant
before insert or update of agent_id, workspace_id
on public.agent_workspace_memberships
for each row execute function control_plane_private.validate_agent_membership();

insert into public.agent_workspace_memberships (
  agent_id, workspace_id, membership_role, can_claim_work, can_delegate_work,
  metadata
)
select
  a.id,
  a.workspace_id,
  case when a.authority_level >= 2 then 'manager' else 'worker' end,
  true,
  a.authority_level >= 2,
  '{"source":"home_workspace_backfill","migration":"v0.4"}'::jsonb
from public.agents a
on conflict (agent_id, workspace_id) do nothing;

create or replace function control_plane_private.ensure_home_workspace_membership()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.agent_workspace_memberships (
    agent_id, workspace_id, membership_role, can_claim_work,
    can_delegate_work, metadata
  ) values (
    new.id,
    new.workspace_id,
    case when new.authority_level >= 2 then 'manager' else 'worker' end,
    true,
    new.authority_level >= 2,
    '{"source":"home_workspace_registration"}'::jsonb
  )
  on conflict (agent_id, workspace_id) do nothing;
  return new;
end;
$$;

create trigger agents_ensure_home_workspace_membership
after insert on public.agents
for each row execute function control_plane_private.ensure_home_workspace_membership();

-- Versioned venture templates describe departments, agent roles, controls,
-- and default task profiles. Provisioning creates identities separately so
-- credentials are still issued once through the gateway.
create table public.venture_blueprints (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  slug text not null
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(trim(name)) between 1 and 160),
  description text,
  status text not null default 'active'
    check (status in ('draft', 'active', 'retired')),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index venture_blueprints_scope_slug_idx
  on public.venture_blueprints (
    coalesce(organization_id, '00000000-0000-0000-0000-000000000000'::uuid),
    slug
  );

create table public.venture_blueprint_versions (
  id uuid primary key default gen_random_uuid(),
  blueprint_id uuid not null
    references public.venture_blueprints(id) on delete cascade,
  version text not null check (length(trim(version)) between 1 and 80),
  definition jsonb not null,
  definition_sha256 text not null,
  status text not null default 'draft'
    check (status in ('draft', 'active', 'retired')),
  created_at timestamptz not null default now(),
  unique (blueprint_id, version)
);

create or replace function control_plane_private.hash_blueprint_definition()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.definition_sha256 := encode(
    extensions.digest(convert_to(new.definition::text, 'UTF8'), 'sha256'),
    'hex'
  );
  return new;
end;
$$;

create trigger venture_blueprint_versions_hash_definition
before insert or update of definition on public.venture_blueprint_versions
for each row execute function control_plane_private.hash_blueprint_definition();

create unique index one_active_venture_blueprint_version
  on public.venture_blueprint_versions (blueprint_id)
  where status = 'active';

create table public.venture_blueprint_instances (
  id uuid primary key default gen_random_uuid(),
  venture_id uuid not null references public.ventures(id) on delete cascade,
  blueprint_version_id uuid not null
    references public.venture_blueprint_versions(id) on delete restrict,
  idempotency_key text not null,
  status text not null default 'planned'
    check (status in ('planned', 'provisioning', 'ready', 'failed', 'retired')),
  provisioned_resources jsonb not null default '{}',
  error jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (venture_id, idempotency_key)
);

create table public.brand_profiles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null
    references public.organizations(id) on delete cascade,
  venture_id uuid references public.ventures(id) on delete cascade,
  product_name text not null check (length(trim(product_name)) between 1 and 160),
  legal_name text,
  logo_url text,
  primary_color text check (primary_color is null or primary_color ~ '^#[0-9A-Fa-f]{6}$'),
  accent_color text check (accent_color is null or accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  support_email text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index one_tenant_default_brand_profile
  on public.brand_profiles (organization_id)
  where venture_id is null;
create unique index one_venture_brand_profile
  on public.brand_profiles (venture_id)
  where venture_id is not null;

create or replace function control_plane_private.validate_venture_tenant_reference()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.venture_id is not null and not exists (
    select 1 from public.ventures v
    where v.id = new.venture_id
      and v.organization_id = new.organization_id
  ) then
    raise exception 'venture reference must belong to the same tenant organization';
  end if;
  return new;
end;
$$;

create trigger brand_profiles_validate_tenant
before insert or update of organization_id, venture_id on public.brand_profiles
for each row execute function control_plane_private.validate_venture_tenant_reference();

-- Provider/model catalog. No provider secret is stored here: credential_ref is
-- an opaque pointer to server-side secret storage such as Supabase Vault.
create table public.model_providers (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(trim(name)) between 1 and 160),
  api_family text not null,
  status text not null default 'active'
    check (status in ('active', 'degraded', 'disabled')),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.model_deployments (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.model_providers(id) on delete restrict,
  organization_id uuid references public.organizations(id) on delete cascade,
  model_key text not null check (length(trim(model_key)) between 1 and 240),
  display_name text not null check (length(trim(display_name)) between 1 and 240),
  endpoint_class text not null default 'hosted'
    check (endpoint_class in ('hosted', 'dedicated', 'self_hosted', 'bot_runtime')),
  credential_ref text,
  capabilities text[] not null default '{}',
  context_window_tokens integer check (context_window_tokens is null or context_window_tokens > 0),
  max_output_tokens integer check (max_output_tokens is null or max_output_tokens > 0),
  input_usd_per_million numeric(12, 6)
    check (input_usd_per_million is null or input_usd_per_million >= 0),
  output_usd_per_million numeric(12, 6)
    check (output_usd_per_million is null or output_usd_per_million >= 0),
  pricing_effective_at timestamptz,
  data_residency text,
  status text not null default 'active'
    check (status in ('active', 'evaluation', 'degraded', 'disabled')),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index model_deployments_scope_key_idx
  on public.model_deployments (
    provider_id,
    coalesce(organization_id, '00000000-0000-0000-0000-000000000000'::uuid),
    model_key,
    endpoint_class
  );

create table public.task_profiles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null
    references public.organizations(id) on delete cascade,
  venture_id uuid references public.ventures(id) on delete cascade,
  slug text not null
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(trim(name)) between 1 and 160),
  required_capabilities text[] not null default '{}',
  risk_tier public.risk_level not null default 'low',
  minimum_quality_score numeric(6, 4)
    check (minimum_quality_score is null or minimum_quality_score between 0 and 1),
  max_latency_ms integer check (max_latency_ms is null or max_latency_ms > 0),
  max_cost_usd numeric(12, 6) check (max_cost_usd is null or max_cost_usd >= 0),
  max_turns smallint not null default 8 check (max_turns between 1 and 100),
  max_tool_calls smallint not null default 20 check (max_tool_calls between 0 and 200),
  allowed_provider_slugs text[] not null default '{}',
  allowed_model_keys text[] not null default '{}',
  data_classification text not null default 'internal'
    check (data_classification in ('public', 'internal', 'confidential', 'restricted')),
  status text not null default 'active'
    check (status in ('draft', 'active', 'retired')),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index task_profiles_scope_slug_idx
  on public.task_profiles (
    organization_id,
    coalesce(venture_id, '00000000-0000-0000-0000-000000000000'::uuid),
    slug
  );

create trigger task_profiles_validate_tenant
before insert or update of organization_id, venture_id on public.task_profiles
for each row execute function control_plane_private.validate_venture_tenant_reference();

create table public.model_routing_policies (
  id uuid primary key default gen_random_uuid(),
  task_profile_id uuid not null references public.task_profiles(id) on delete cascade,
  version text not null check (length(trim(version)) between 1 and 80),
  strategy text not null default 'balanced'
    check (strategy in ('quality_first', 'balanced', 'cost_first', 'latency_first', 'fixed')),
  quality_weight numeric(6, 4) not null default 0.5 check (quality_weight between 0 and 1),
  cost_weight numeric(6, 4) not null default 0.3 check (cost_weight between 0 and 1),
  latency_weight numeric(6, 4) not null default 0.2 check (latency_weight between 0 and 1),
  fallback_model_deployment_ids uuid[] not null default '{}',
  rules jsonb not null default '{}',
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  check (quality_weight + cost_weight + latency_weight = 1),
  unique (task_profile_id, version)
);

create unique index one_active_model_routing_policy
  on public.model_routing_policies (task_profile_id)
  where is_active;

create table public.model_routing_decisions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete restrict,
  work_item_id uuid references public.work_items(id) on delete set null,
  attempt_id uuid references public.work_attempts(id) on delete set null,
  task_profile_id uuid not null references public.task_profiles(id) on delete restrict,
  routing_policy_id uuid not null references public.model_routing_policies(id) on delete restrict,
  selected_model_deployment_id uuid not null
    references public.model_deployments(id) on delete restrict,
  candidate_snapshot jsonb not null,
  estimated_input_tokens integer not null default 0 check (estimated_input_tokens >= 0),
  estimated_output_tokens integer not null default 0 check (estimated_output_tokens >= 0),
  estimated_cost_usd numeric(12, 6) not null check (estimated_cost_usd >= 0),
  reason text not null,
  created_at timestamptz not null default now()
);

create index model_routing_decisions_work_idx
  on public.model_routing_decisions (workspace_id, work_item_id, created_at);
create index model_routing_decisions_profile_idx
  on public.model_routing_decisions (task_profile_id, created_at);

create or replace function control_plane_private.validate_model_routing_decision()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  workspace_organization_id uuid;
  profile_organization_id uuid;
  policy_profile_id uuid;
  deployment_organization_id uuid;
begin
  select organization_id into workspace_organization_id
  from public.workspaces where id = new.workspace_id;
  select organization_id into profile_organization_id
  from public.task_profiles where id = new.task_profile_id;
  select task_profile_id into policy_profile_id
  from public.model_routing_policies where id = new.routing_policy_id;
  select organization_id into deployment_organization_id
  from public.model_deployments where id = new.selected_model_deployment_id;

  if workspace_organization_id is null
     or profile_organization_id <> workspace_organization_id then
    raise exception 'routing task profile must belong to the workspace tenant';
  end if;
  if policy_profile_id is distinct from new.task_profile_id then
    raise exception 'routing policy does not belong to the selected task profile';
  end if;
  if deployment_organization_id is not null
     and deployment_organization_id <> workspace_organization_id then
    raise exception 'model deployment is not available to the workspace tenant';
  end if;
  return new;
end;
$$;

create trigger model_routing_decisions_validate_scope
before insert on public.model_routing_decisions
for each row execute function control_plane_private.validate_model_routing_decision();

alter table public.eval_results
  add column task_profile_id uuid references public.task_profiles(id) on delete set null,
  add column model_deployment_id uuid references public.model_deployments(id) on delete set null;

alter table public.usage_ledger
  add column routing_decision_id uuid
    references public.model_routing_decisions(id) on delete set null,
  add column model_deployment_id uuid
    references public.model_deployments(id) on delete set null,
  add column estimated_cost_usd numeric(12, 6)
    check (estimated_cost_usd is null or estimated_cost_usd >= 0);

-- Venture budgets coexist with existing workspace and global budgets.
alter table public.budgets
  add column venture_id uuid references public.ventures(id) on delete cascade,
  add column reserved_usd numeric(12, 6) not null default 0
    check (reserved_usd >= 0);

alter table public.budgets
  drop constraint if exists budgets_scope_type_check,
  drop constraint if exists budgets_workspace_scope_check;
alter table public.budgets
  add constraint budgets_scope_type_check check (
    scope_type in ('global', 'venture', 'workspace', 'agent', 'workflow', 'customer')
  ),
  add constraint budgets_scope_reference_check check (
    (scope_type = 'global' and workspace_id is null and venture_id is null)
    or (scope_type = 'venture' and workspace_id is null and venture_id is not null)
    or (scope_type not in ('global', 'venture') and workspace_id is not null and venture_id is null)
  );

drop index if exists public.budgets_scope_period_idx;
create unique index budgets_scope_period_idx
  on public.budgets (
    coalesce(venture_id, '00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(workspace_id, '00000000-0000-0000-0000-000000000000'::uuid),
    scope_type,
    scope_id,
    period_start,
    period_end
  );

create table public.model_budget_reservations (
  id uuid primary key default gen_random_uuid(),
  budget_id uuid not null references public.budgets(id) on delete restrict,
  routing_decision_id uuid not null
    references public.model_routing_decisions(id) on delete restrict,
  estimated_cost_usd numeric(12, 6) not null check (estimated_cost_usd >= 0),
  actual_cost_usd numeric(12, 6) check (actual_cost_usd is null or actual_cost_usd >= 0),
  status text not null default 'reserved'
    check (status in ('reserved', 'settled', 'released', 'over_limit')),
  expires_at timestamptz not null,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  unique (routing_decision_id),
  check (expires_at > created_at)
);

create index model_budget_reservations_active_idx
  on public.model_budget_reservations (budget_id, expires_at)
  where status = 'reserved';

create function public.reserve_model_budget(
  p_budget_id uuid,
  p_routing_decision_id uuid,
  p_estimated_cost_usd numeric,
  p_ttl_seconds integer default 900
)
returns public.model_budget_reservations
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected_budget public.budgets;
  existing_reservation public.model_budget_reservations;
  created_reservation public.model_budget_reservations;
begin
  if p_estimated_cost_usd < 0 then
    raise exception 'estimated model cost must be non-negative';
  end if;
  if p_ttl_seconds < 30 or p_ttl_seconds > 3600 then
    raise exception 'reservation TTL must be between 30 and 3600 seconds';
  end if;

  select * into existing_reservation
  from public.model_budget_reservations
  where routing_decision_id = p_routing_decision_id;
  if found then
    return existing_reservation;
  end if;

  select * into selected_budget
  from public.budgets
  where id = p_budget_id
    and period_start <= now()
    and period_end > now()
  for update;

  if not found then
    raise exception 'active budget does not exist';
  end if;
  if not exists (
    select 1
    from public.model_routing_decisions rd
    join public.workspaces w on w.id = rd.workspace_id
    where rd.id = p_routing_decision_id
      and (
        selected_budget.scope_type = 'global'
        or (
          selected_budget.scope_type = 'venture'
          and w.venture_id = selected_budget.venture_id
        )
        or (
          selected_budget.scope_type not in ('global', 'venture')
          and rd.workspace_id = selected_budget.workspace_id
        )
      )
  ) then
    raise exception 'budget scope does not cover the routing decision';
  end if;
  if selected_budget.spent_usd + selected_budget.reserved_usd
       + p_estimated_cost_usd > selected_budget.hard_limit_usd then
    raise exception 'budget hard limit would be exceeded';
  end if;

  insert into public.model_budget_reservations (
    budget_id, routing_decision_id, estimated_cost_usd, expires_at
  ) values (
    p_budget_id, p_routing_decision_id, p_estimated_cost_usd,
    now() + make_interval(secs => p_ttl_seconds)
  ) returning * into created_reservation;

  update public.budgets
  set reserved_usd = reserved_usd + p_estimated_cost_usd,
      updated_at = now()
  where id = p_budget_id;

  return created_reservation;
end;
$$;

create function public.settle_model_budget(
  p_reservation_id uuid,
  p_actual_cost_usd numeric
)
returns public.model_budget_reservations
language plpgsql
security invoker
set search_path = ''
as $$
declare
  reservation public.model_budget_reservations;
  selected_budget public.budgets;
  final_status text;
begin
  if p_actual_cost_usd < 0 then
    raise exception 'actual model cost must be non-negative';
  end if;

  select * into reservation
  from public.model_budget_reservations
  where id = p_reservation_id
  for update;
  if not found or reservation.status <> 'reserved' then
    raise exception 'active model budget reservation does not exist';
  end if;

  select * into selected_budget
  from public.budgets
  where id = reservation.budget_id
  for update;

  final_status := case
    when selected_budget.spent_usd + p_actual_cost_usd
           > selected_budget.hard_limit_usd then 'over_limit'
    else 'settled'
  end;

  update public.budgets
  set reserved_usd = greatest(0, reserved_usd - reservation.estimated_cost_usd),
      spent_usd = spent_usd + p_actual_cost_usd,
      updated_at = now()
  where id = selected_budget.id;

  update public.model_budget_reservations
  set actual_cost_usd = p_actual_cost_usd,
      status = final_status,
      settled_at = now()
  where id = p_reservation_id
  returning * into reservation;

  return reservation;
end;
$$;

create function public.release_expired_model_budget_reservations()
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  reservation public.model_budget_reservations;
  released integer := 0;
begin
  for reservation in
    select * from public.model_budget_reservations
    where status = 'reserved' and expires_at <= now()
    for update skip locked
  loop
    update public.budgets
    set reserved_usd = greatest(0, reserved_usd - reservation.estimated_cost_usd),
        updated_at = now()
    where id = reservation.budget_id;

    update public.model_budget_reservations
    set status = 'released', settled_at = now()
    where id = reservation.id;
    released := released + 1;
  end loop;
  return released;
end;
$$;

-- Seed one global, versioned operating blueprint. It is only a plan; no agent
-- credentials or outbound permissions are created by this seed.
insert into public.venture_blueprints (
  organization_id, slug, name, description, status, metadata
) values (
  null,
  'lean-b2b-service',
  'Lean B2B Service Venture',
  'A reusable research-to-revenue operating design for a human-governed agentic venture.',
  'active',
  '{"category":"agentic_venture_studio","white_label_ready":true}'::jsonb
)
on conflict do nothing;

insert into public.venture_blueprint_versions (
  blueprint_id, version, definition, status
)
select
  b.id,
  '1.0.0',
  '{
    "workspaces": [
      {"slug":"executive","kind":"department","name":"Executive"},
      {"slug":"market-intelligence","kind":"department","name":"Market Intelligence"},
      {"slug":"sales","kind":"department","name":"Sales"},
      {"slug":"delivery","kind":"department","name":"Delivery"},
      {"slug":"finance-ops","kind":"department","name":"Finance / Ops"},
      {"slug":"red-team-qa","kind":"department","name":"Red Team / QA"}
    ],
    "agent_roles": [
      {"key":"chief-of-staff","authority_level":2,"home_workspace":"executive"},
      {"key":"market-intelligence","authority_level":1,"home_workspace":"market-intelligence"},
      {"key":"sales","authority_level":1,"home_workspace":"sales"},
      {"key":"delivery","authority_level":1,"home_workspace":"delivery"},
      {"key":"finance-ops","authority_level":1,"home_workspace":"finance-ops"},
      {"key":"red-team-qa","authority_level":1,"home_workspace":"red-team-qa"}
    ],
    "controls": {
      "outbound_actions_disabled": true,
      "human_approval_required": ["send","spend","publish","delete","permissions","production"]
    }
  }'::jsonb,
  'active'
from public.venture_blueprints b
where b.organization_id is null and b.slug = 'lean-b2b-service'
on conflict (blueprint_id, version) do nothing;

-- Updated timestamps on mutable catalogs.
create trigger ventures_set_updated_at before update on public.ventures
for each row execute function control_plane_private.set_updated_at();
create trigger agent_workspace_memberships_set_updated_at
before update on public.agent_workspace_memberships
for each row execute function control_plane_private.set_updated_at();
create trigger venture_blueprints_set_updated_at before update on public.venture_blueprints
for each row execute function control_plane_private.set_updated_at();
create trigger venture_blueprint_instances_set_updated_at
before update on public.venture_blueprint_instances
for each row execute function control_plane_private.set_updated_at();
create trigger brand_profiles_set_updated_at before update on public.brand_profiles
for each row execute function control_plane_private.set_updated_at();
create trigger model_providers_set_updated_at before update on public.model_providers
for each row execute function control_plane_private.set_updated_at();
create trigger model_deployments_set_updated_at before update on public.model_deployments
for each row execute function control_plane_private.set_updated_at();
create trigger task_profiles_set_updated_at before update on public.task_profiles
for each row execute function control_plane_private.set_updated_at();

create index ventures_organization_status_idx
  on public.ventures (organization_id, status, created_at);
create index workspaces_venture_status_idx
  on public.workspaces (venture_id, status, created_at)
  where venture_id is not null;
create index agent_workspace_memberships_workspace_idx
  on public.agent_workspace_memberships (workspace_id, status, agent_id);
create index model_deployments_provider_status_idx
  on public.model_deployments (provider_id, status, created_at);
create index eval_results_model_profile_idx
  on public.eval_results (model_deployment_id, task_profile_id, created_at)
  where model_deployment_id is not null;

-- All new public tables are server-only. Agents continue to enter through the
-- custom-auth gateway, which alone holds service_role credentials.
alter table public.ventures enable row level security;
alter table public.ventures force row level security;
alter table public.agent_workspace_memberships enable row level security;
alter table public.agent_workspace_memberships force row level security;
alter table public.venture_blueprints enable row level security;
alter table public.venture_blueprints force row level security;
alter table public.venture_blueprint_versions enable row level security;
alter table public.venture_blueprint_versions force row level security;
alter table public.venture_blueprint_instances enable row level security;
alter table public.venture_blueprint_instances force row level security;
alter table public.brand_profiles enable row level security;
alter table public.brand_profiles force row level security;
alter table public.model_providers enable row level security;
alter table public.model_providers force row level security;
alter table public.model_deployments enable row level security;
alter table public.model_deployments force row level security;
alter table public.task_profiles enable row level security;
alter table public.task_profiles force row level security;
alter table public.model_routing_policies enable row level security;
alter table public.model_routing_policies force row level security;
alter table public.model_routing_decisions enable row level security;
alter table public.model_routing_decisions force row level security;
alter table public.model_budget_reservations enable row level security;
alter table public.model_budget_reservations force row level security;

create policy deny_direct_agent_access on public.ventures
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.agent_workspace_memberships
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.venture_blueprints
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.venture_blueprint_versions
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.venture_blueprint_instances
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.brand_profiles
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.model_providers
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.model_deployments
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.task_profiles
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.model_routing_policies
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.model_routing_decisions
  for all to anon, authenticated using (false) with check (false);
create policy deny_direct_agent_access on public.model_budget_reservations
  for all to anon, authenticated using (false) with check (false);

revoke all on public.ventures from public, anon, authenticated;
revoke all on public.agent_workspace_memberships from public, anon, authenticated;
revoke all on public.venture_blueprints from public, anon, authenticated;
revoke all on public.venture_blueprint_versions from public, anon, authenticated;
revoke all on public.venture_blueprint_instances from public, anon, authenticated;
revoke all on public.brand_profiles from public, anon, authenticated;
revoke all on public.model_providers from public, anon, authenticated;
revoke all on public.model_deployments from public, anon, authenticated;
revoke all on public.task_profiles from public, anon, authenticated;
revoke all on public.model_routing_policies from public, anon, authenticated;
revoke all on public.model_routing_decisions from public, anon, authenticated;
revoke all on public.model_budget_reservations from public, anon, authenticated;

grant select, insert, update on public.ventures to service_role;
grant select, insert, update on public.agent_workspace_memberships to service_role;
grant select, insert, update on public.venture_blueprints to service_role;
grant select, insert, update on public.venture_blueprint_versions to service_role;
grant select, insert, update on public.venture_blueprint_instances to service_role;
grant select, insert, update on public.brand_profiles to service_role;
grant select, insert, update on public.model_providers to service_role;
grant select, insert, update on public.model_deployments to service_role;
grant select, insert, update on public.task_profiles to service_role;
grant select, insert, update on public.model_routing_policies to service_role;
grant select, insert on public.model_routing_decisions to service_role;
grant select, insert, update on public.model_budget_reservations to service_role;

revoke all on function public.reserve_model_budget(uuid, uuid, numeric, integer)
  from public, anon, authenticated;
revoke all on function public.settle_model_budget(uuid, numeric)
  from public, anon, authenticated;
revoke all on function public.release_expired_model_budget_reservations()
  from public, anon, authenticated;
grant execute on function public.reserve_model_budget(uuid, uuid, numeric, integer)
  to service_role;
grant execute on function public.settle_model_budget(uuid, numeric)
  to service_role;
grant execute on function public.release_expired_model_budget_reservations()
  to service_role;

revoke all on all functions in schema control_plane_private
  from public, anon, authenticated, service_role;

commit;
